### ISSUE TITLE
Test files breaking the compilation for ESP8266 

### ISSUE THREAD

**Issue by ericonetto** [ssilverman/libCBOR#1]
If you create a project in Platformio for a ESP8266, and refer the dependency in platformio.ini to libCBOR, like this example below:

> [env:esp12e]
> platform = espressif8266
> board = esp12e
> framework = arduino
> 
> lib_deps = ESP8266HTTPClient
>            ESP8266WiFi
>            https://github.com/ssilverman/libCBOR

Then when you try to compile the project, it will breack  because of the test files included in the library are for Arduino enviroment. 

Gives a message like this:

> platformio run
> Compiling .pioenvs/esp12e/lib/libCBOR/CBOR_streams.o
> Compiling .pioenvs/esp12e/lib/libCBOR/CBOR_utils.o
> 
> Compiling .pioenvs/esp12e/lib/libCBOR/tests.o
> .piolibdeps/libCBOR/src/tests.cpp:12:25: fatal error: ArduinoUnit.h: No such file or directory
> #include <ArduinoUnit.h>
> ^
> compilation terminated.
> *** [.pioenvs/esp12e/lib/libCBOR/tests.o] Error 1
> ========================== [ERROR] Took 7.94 seconds ==========================

**Comment by ssilverman** [comment]
In order to add libCBOR as a library to your project, simply remove `tests.h`, `tests.cpp`, and the `tests/` directory. That should fix the compilation problems.

I'm working on understanding how best to include tests in a project intended as an Arduino library, but easily exclude them when installing the library.

Hope this helps.

**Comment by ssilverman** [comment]
I'm also really surprised the compiler includes the tests, but I suppose it may have something to do with the fact that there's a setup() and loop() in there.

**Comment by ssilverman** [comment]
I've just created a new release, v1.3.1, that moves all the tests to a src_tests folder. This should resolve the issue.

**Comment by ericonetto** [comment]
I'll test tomorrow.  Good to know you've managed a way around this issue. Thanks

**Comment by ericonetto** [comment]
Now it compiles well. Thanks.
