### ISSUE TITLE
How to get CBOR bytes?

### ISSUE THREAD

**Issue by skhaz** [ssilverman/libCBOR#6]
Hi, first of all, thank you for creating this library. Secondly, I have a question about how to obtain the written bytes. In the example below, shouldn't getWriteSize return a non-zero value? Or is there another method?

I ask this because my payload will have values of 0, and I cannot use strlen as it would break in half due to the zeros.

How can I obtain the bytes in CBOR?

```
uint8_t bytes[kBytesSize]{0};
cbor::BytesStream bs{bytes, sizeof(bytes)};
cbor::BytesPrint bp{bytes, sizeof(bytes)};

cbor::Writer cbor{bs};

bs.reset();

cbor.writeTag(cbor::kSelfDescribeTag);
cbor.beginArray(2);
cbor.writeUnsignedInt(0);
cbor.writeUnsignedInt(1);
cbor.flush();
size_t size = cbor.getWriteSize();
```

`size` is 0.

**Comment by ssilverman** [comment]
Could you please provide a complete program that demonstrates the problem?

**Comment by ssilverman** [comment]
Try with the `BytesPrint` instead of the `BytesStream`. I looked at the `BytesStream` header docs and noticed that I had intended it to be input-only; all the write functions do nothing.

**Comment by skhaz** [comment]
@ssilverman Indeed, changing to BytesPrint worked fine.

My code, if anyone else needs to publish CBOR over MQTT:

Init:
```cpp
PubSubClient pubsub(AWS_IOT_ENDPOINT, AWS_IOT_PORT, net);

constexpr size_t kBytesSize = 256;
uint8_t bytes[kBytesSize]{0};
cbor::BytesStream bs{bytes, sizeof(bytes)};
cbor::BytesPrint bp{bytes, sizeof(bytes)};
```

Loop:
```cpp
cbor::Writer cbor{bp};

bp.reset();

cbor.beginArray(2);
cbor.writeDouble(latitude);
cbor.writeDouble(longitude);

size_t lenght = cbor.getWriteSize();

Serial.print("Payload lenght: ");
Serial.printf("%zu", lenght);
Serial.print(" bytes.");
Serial.println();

pubsub.publish(TOPIC, reinterpret_cast<const uint8_t *>(&bytes), lenght, false);
```

**Comment by ssilverman** [comment]
Sounds like the issue was resolved; closing.
